import { Product, ProductCategory, StockStatus } from '../../../constants';

export const products: Product[] = [
  {
    id: 1,
    name: 'Laptop',
    price: 999,
    category: ProductCategory.ELECTRONICS,
    description: 'A powerful laptop.',
    sku: 'E123',
    stock: StockStatus.IN_STOCK,
  },
  {
    id: 2,
    name: 'T-Shirt',
    price: 19.99,
    category: ProductCategory.FASHION,
    description: 'A stylish t-shirt.',
    sku: 'F456',
    stock: StockStatus.OUT_OF_STOCK,
  },
  {
    id: 3,
    name: 'Book',
    price: 12.5,
    category: ProductCategory.BOOKS,
    description: 'A bestselling novel.',
    sku: 'B789',
    stock: StockStatus.OUT_OF_STOCK,
  },
  {
    id: 4,
    name: 'Laptop',
    price: 999,
    category: ProductCategory.ELECTRONICS,
    description: 'A powerful laptop.',
    sku: 'E123',
    stock: StockStatus.IN_STOCK,
  },
  {
    id: 5,
    name: 'T-Shirt',
    price: 19.99,
    category: ProductCategory.FASHION,
    description: 'A stylish t-shirt.',
    sku: 'F456',
    stock: StockStatus.OUT_OF_STOCK,
  },
  {
    id: 6,
    name: 'Book',
    price: 12.5,
    category: ProductCategory.BOOKS,
    description: 'A bestselling novel.',
    sku: 'B789',
    stock: StockStatus.OUT_OF_STOCK,
  },
  {
    id: 7,
    name: 'Laptop',
    price: 999,
    category: ProductCategory.ELECTRONICS,
    description: 'A powerful laptop.',
    sku: 'E123',
    stock: StockStatus.IN_STOCK,
  },
  {
    id: 8,
    name: 'T-Shirt',
    price: 19.99,
    category: ProductCategory.FASHION,
    description: 'A stylish t-shirt.',
    sku: 'F456',
    stock: StockStatus.OUT_OF_STOCK,
  },
  {
    id: 9,
    name: 'Book',
    price: 12.5,
    category: ProductCategory.BOOKS,
    description: 'A bestselling novel.',
    sku: 'B789',
    stock: StockStatus.OUT_OF_STOCK,
  },
  {
    id: 10,
    name: 'Laptop',
    price: 999,
    category: ProductCategory.ELECTRONICS,
    description: 'A powerful laptop.',
    sku: 'E123',
    stock: StockStatus.IN_STOCK,
  },
  {
    id: 11,
    name: 'T-Shirt',
    price: 19.99,
    category: ProductCategory.FASHION,
    description: 'A stylish t-shirt.',
    sku: 'F456',
    stock: StockStatus.OUT_OF_STOCK,
  },
  {
    id: 12,
    name: 'Book',
    price: 12.5,
    category: ProductCategory.BOOKS,
    description: 'A bestselling novel.',
    sku: 'B789',
    stock: StockStatus.OUT_OF_STOCK,
  },
  {
    id: 13,
    name: 'Laptop',
    price: 999,
    category: ProductCategory.ELECTRONICS,
    description: 'A powerful laptop.',
    sku: 'E123',
    stock: StockStatus.IN_STOCK,
  },
  {
    id: 14,
    name: 'T-Shirt',
    price: 19.99,
    category: ProductCategory.FASHION,
    description: 'A stylish t-shirt.',
    sku: 'F456',
    stock: StockStatus.OUT_OF_STOCK,
  },
  {
    id: 15,
    name: 'Book',
    price: 12.5,
    category: ProductCategory.BOOKS,
    description: 'A bestselling novel.',
    sku: 'B789',
    stock: StockStatus.OUT_OF_STOCK,
  },
];
